zoom in: edit.zoom_in()
zoom out: edit.zoom_out()
zoom reset: edit.zoom_reset()
scroll up: edit.page_up()
scroll down: edit.page_down()
copy [that]: key(ctrl-c)
cut (this | that): key(ctrl-x)
paste that: key(ctrl-v)
undo that: edit.undo()
redo that: edit.redo()
paste match: edit.paste_match_style()
save that: edit.save()
kill: key(backspace)
(pad | padding): user.insert_between(" ", " ")
slap: edit.line_insert_down()
