language:/.*/
-
meme it is what it is: "https://www.youtube.com/watch?v=Vm1yHwwfAic"
meme team data: "https://www.youtube.com/watch?v=2y4xKNt_kbM"
meme impossible: "https://www.youtube.com/watch?v=Q9-fYdy12PY"
meme (super boy | super Junge): "https://www.youtube.com/watch?v=IqssrGv6UNI&t=54s"

meme (hot | heiß): "https://www.youtube.com/watch?v=ZLN7Vx2ZVHk&t=96s"
meme (honk): "https://www.youtube.com/watch?v=2sIKYlxDxwE"
meme (long | long man): "https://www.youtube.com/watch?v=6-1Ue0FFrHY&amp;t=13s"
meme (alarm | alert): "https://www.youtube.com/watch?v=tc-pRTk2r7k"
meme (latest shit): "Denn ganz ehrlich, wo ist hier, wo ist der latest shit, ne? Wo ist das denn, wo passiert das denn? Wo ist der Merger, wo ist hier Fashion, wo ist Musik, wo ist Architektur? Ich seh so'n paar Prints, 'n paar Poster, aber das isses doch nicht. Bauhaus, was soll das denn? Die werden jetzt 100 Jahre alt nächstes Jahr. Kann ich doch mich – Ich kann mich doch daran nicht mehr erlabern, das muss doch weitergehen. Wo sind die Magazine, wo ist die Inspiration, wo ist Augumented Reality, wo ist das alles, wo sind die Oculus Rift-Brillen? Das ist alles so in der Komfortzone."
meme machine learning: "https://youtu.be/YnL9vAFphmE?t=146"

meme Friday: "https://www.youtube.com/watch?v=kfVsfOSbJY0&t=98s"
meme Friday alternative: "https://www.youtube.com/watch?v=kfVsfOSbJY0&t=128s"
meme Thursday: "https://www.youtube.com/watch?v=kfVsfOSbJY0&t=125s"
meme Saturday: "https://www.youtube.com/watch?v=kfVsfOSbJY0&t=142s"
meme partying: "https://www.youtube.com/watch?v=kfVsfOSbJY0&t=62s"

meme Friday let's go: "https://youtube.com/shorts/cjgldht4PKw"

meme deadline mode: "https://www.youtube.com/watch?v=SFvbXZAaHTY"

meme guy staring: "https://www.youtube.com/watch?v=52XqcGgjP_4"
meme never give up: "https://www.youtube.com/watch?v=tYzMYcUty6s"

emote (smile tears | lachen Tränen): "😂"
emote (smile sweat | lachen schwitzen): "😅"
emote (smile smile | lachen lachen): "😄"
emote (smile wink | lachen zwinkern): "😉"
emote (smile rolling | lachen Rollen): "🤣"
emote (muscle | Muskel): "💪"
emote (shrug | Achselzucken): "🤷"
emote (pix drum | X D): ️"😆"
emote (sunglasses | Sonnenbrille): "😎"
emote (shocking | Schock): "😱"
emote (squiggly face | Wabl Gesicht): "🥴"
emote (beers | Biere): "🍻"
emote (egg plant | Auberginen): "🍆"
emote (banana | Banane): "🍌"
emote (sick | übel): "🤢"
emote (weary | müde): "😩"
emote (idea | Idee): "💡"
emote (birthday cake | Geburtstagstorte): "🎂"
emote (kiss | Küsschen): "😘"
emote (heart face | Herz Gesicht): "🥰"
emote (heart eyes | Herz Augen): "😍"
emote (index finger | Zeigefinger): "☝"
emote (beer | wir): ️"🍺"
emote (pizza): "🍕"
emote (heart with arrow | Herz mit Pfeil): "💘"
emote (head explodes | Kopf explodiert): "🤯"
emote (beard | Bart): "🥸"
emote (queen | Königin): "👸"
emote (king | König): "🤴"
emote (crown | Krone): "👑"
emote (Hammer): "🔨"
emote (Party): "🥳"
emote (Cocktail): "🍹"
emote (party horn | Party Tröte): "🎉"
emote (wine | Wein): "🍷"
